sudo: false
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
cache:
  directories:
    - $HOME/.cache/pip
install: pip install tox-travis coveralls coverage flake8
script: tox

after_success:
  - coverage report
  - coveralls
